### PR TITLE
Changes to index.html and book appointment.html

### PR DESCRIPTION
**Pull request by KateZhuzha**
test

### CODE REVIEW

**Comment by KateZhuzha** [comment]
Pulling the changes I have made today: full edit, new content, new links

**Comment by MarCampsSallent** [comment]
dont forget to add a comment!

**Comment by KateZhuzha** [comment]
Confirming I'm adding a comment to the pull, to commit to the master the changes I made today

**Comment by KateZhuzha** [comment]
YAY! THANK YOU!

**Comment by MarCampsSallent** [comment]
Decide which parts to keep:

highlighted are the ones that have a significant update.

Here more info: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

**Pull request merged**
